### ISSUE TITLE
老哥打扰下

### ISSUE THREAD

**Issue by kkh66** [ddv12138/MCSManager#1]
能不能问下你的这个有没有对docker支持

**Comment by ddv12138** [comment]
我这个不就是docker的么

**Comment by kkh66** [comment]
> 我这个不就是docker的么

是的我发现你这个如果打算在服务器哪里在开docker好像不行好像是因为没环境

**Comment by kkh66** [comment]
> > 我这个不就是docker的么
> 
> 是的我发现你这个如果打算在服务器哪里在开docker好像不行好像是因为没环境

虽然有点搞笑在docker开docker

**Comment by ddv12138** [comment]
其实是可以支持，但是没必要，把宿主的docker的socket映射到容器里就行，但是这样并不好，相当于该容器里面可以控制其他容器，尽管我最新的镜像已经做了这个功能，你可以去[这里](https://hub.docker.com/r/ddv12138/mcsmanager)看下

**Comment by ddv12138** [comment]
另外我写这个dockerfile的时候[原项目](http://mcsm.suwings.top/)是有问题的，它那个nodejs上传文件一直有问题，提了issue他说改了实测也没有改好，所以我还是转向使用java的docker镜像直接起mc了

**Comment by kkh66** [comment]
> 其实是可以支持，但是没必要，把宿主的docker的socket映射到容器里就行，但是这样并不好，相当于该容器里面可以控制其他容器，尽管我最新的镜像已经做了这个功能，你可以去[这里](https://hub.docker.com/r/ddv12138/mcsmanager)看下

 哦哦，感谢老哥答复我。
